detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    public_methods_only: true
    exclude:
      - "#authorize"

  FeatureEnvy:
    enabled: false

  ControlParameter:
    enabled: false

exclude_paths:
  - db/migrate