---
detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    enabled: true
    exclude: [ 'initialize' ]
    max_statements: 10

  UtilityFunction:
    public_methods_only: true
    exclude: [ '#authorize' ]

  FeatureEnvy:
    enabled: false

  ControlParameter:
    enabled: false

exclude_paths: [ 'db/migrate' ]